spring.application.name=EgreExperience

spring.datasource.url=jdbc:mysql://localhost:3306/EgreExperience
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update